config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :topics do
    resources :articles
  end
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  extend FriendlyId
  friendly_id :name
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @article = @topic.articles.create(article_params)
    if @article.save
      redirect_to( @topic )
    else
      redirect_to (@topic)
    end
  end

  def edit
    @topic = Topic.friendly.find(params[:topic_id])
    @article = Article.find(params[:id])
  end

  def new
    @topic = Topic.friendly.find(params[:topic_id])
    @article = Article.new
  end

  def update
    @article = Article.find(params[:id])
    @topic = Topic.friendly.find(params[:topic_id])
    if @article.update(article_params)
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def show
    @article = Article.find(params[:id])
    @topic = Topic.friendly.find(params[:topic_id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = 'Article has been deleted'
    redirect_to topics_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :author, :body, :published, :thumbnail)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    @articles = Article.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to( @topic )
    else
      render 'new'
    end
  end

  def destroy
    @topic = Topic.friendly.find(params[:id])
    @topic.destroy
    flash[:notice] = 'Topic has been deleted'
    redirect_to topics_path
  end

  def show
    @topic = Topic.friendly.find(params[:id])
    @comment = Article.new
    @articles = @topic.articles
  end

  private

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.3.7"
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article_form.html.erb
<%= form_for([@topic, @article]) do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body, :rows => 10, style: 'width:100%;'%>
  </p>

  <p>
    <%= f.label :thumbnail %>
    <%= f.text_field :thumbnail %>
  </p>

  <p>
    <%= f.submit 'Submit', :class => 'btn btn-success'%>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'article_form' %>
<%= link_to 'Back', topic_article_path(@topic, @article), class: 'btn btn-primary' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<ul class="list-group">
  <% @articles.each do |article| %>
    <li class="list-group-item">
      <%= link_to(image_tag(article.thumbnail), article_path(article), class: "article-link") %>
    </li>
  <% end %>
</ul>
<iframe width="560" height="315" src="https://www.youtube.com/embed/live_stream?channel=paridonn1"></iframe>
<br>

<%= link_to "New Article", new_article_path, class: "btn btn-primary" %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'article_form', topic: @topic, article: @article %>
<%= link_to 'Back', articles_path, class: 'btn btn-primary' %>

app/views/articles/show.html.erb
<table style="width:90%">
  <tr>
    <th>
      <%= @article.title %>
    </th>
  </tr>
    <td>
      <% if @article.thumbnail != nil %>
      <%= image_tag(@article.thumbnail)%>
      <% end %>
    </td>
  <tr>
    <th>
      By: <%= @article.author %>
    </th>
  </tr>
  <tr>
    <td>
      <%= @article.body %>
    </td>
  </tr>
  <tr>
    <td class="piano-content">

    </td>
  </tr>
</table>

<%= link_to "Back to #{@topic.name}", topic_path(@topic), class: "btn btn-primary" %>
<%= link_to 'Edit Article', edit_topic_article_path(@topic, @article), class: "btn btn-warning" %>
<%= link_to 'Delete Article', @article, method: :delete, class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PianoTestSite</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script>
      document.cookie = "__adblocker=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/";
      var setNptTechAdblockerCookie = function(adblocker) {
          var d = new Date();
          d.setTime(d.getTime() + 60 * 60 * 24 * 2 * 1000);
          document.cookie = "__adblocker=" + (adblocker ? "true" : "false") + "; expires=" + d.toUTCString() + "; path=/";
      }
      var script = document.createElement("script");
      script.setAttribute("async", true);
      script.setAttribute("src", "//www.npttech.com/advertising.js");
      script.setAttribute("onerror", "setNptTechAdblockerCookie(true);");
      document.getElementsByTagName("head")[0].appendChild(script);
  </script>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/topics">World News</a>
          </div>
          <ul class="nav navbar-nav">
            <li><a href="/topics/News">News</a></li>
            <li><a href="/topics/Lifestyle">Lifestyle</a></li>
            <li><a href="/topics/Sports">Sports</a></li>
            <li><a id="test-button" href="#">Button</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#" id="login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <li><a href="#" id="logout"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
            <li><a href="#" id="signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="#" id="myaccount"><span class="glyphicon glyphicon-user"></span> My Account</a></li>
            <li><a href="https://sandbox.tinypass.com/id/api/v1/identity/vxauth/authorize?response_type=code&client_id=oiGmjC8JwK&redirect_uri=http://localhost:3000"><span class="glyphicon glyphicon-user"></span>oAuth</a></li>
"
          </ul>
        </div>
      </nav>
      <div id="piano-test-container"></div>
      <script>
      tp = window.tp || [];
        (function(src) {
              var a = document.createElement("script");
              a.type = "text/javascript";
              a.async = true;
              a.src = src;
              var b = document.getElementsByTagName("script")[0];
              b.parentNode.insertBefore(a, b)
          })("//sandbox.tinypass.com/xbuilder/experience/load?aid=oiGmjC8JwK");

      tp.push(["init", function(){
        if (tp.pianoId.isUserValid()) {
          $("#login").hide()
          $("#signup").hide()
        } else {
          $('#myaccount').hide()
          $("#logout").hide()
        }

        document.getElementById('login').onclick = function() {
          tp.pianoId.show({
            screen: 'login',
            displayMode: 'modal',
            loggedIn: function(){
                  location.reload();
              }
            })
          }

          document.getElementById('signup').onclick = function() {
            tp.pianoId.show({
              screen: 'register',
              displayMode: 'modal',
              loggedIn: function(){
                    location.reload();
                }
              })
            }

          document.getElementById('logout').onclick = function(){
            tp.pianoId.logout();
              location.reload();
            }

          document.getElementById('myaccount').onclick = function() {
            tp.myaccount.show({
                displayMode: "inline",
                containerSelector: "#account-info"
              })
            }
        }])


      </script>
      <%= yield %>
    </div>
    <div id="account-info">
    <script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for (@topic) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

    <%= f.submit 'Submit', :class => 'btn btn-success'%>
  </p>

<% end %>

app/views/topics/index.html.erb
<div class="row">
  <div class="card-deck">
    <% @articles.each do |article| %>
      <%= link_to topic_article_path(article.topic, article) do %>
        <div class="card" style="width: 20rem;">
        <img class="card-img-top" src="<%= article.thumbnail %>" height="90" alt="<%= article.title %>">
          <div class="card-block">
            <h4 class="card-title"><%= article.title %></h4>
            <p class="card-text">By <%= article.author %></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><%= article.created_at %></small>
          </div>
        </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= render 'form', topic: @topic %>
<%= link_to 'Back', topics_path, class: 'btn btn-primary' %>

app/views/topics/show.html.erb
<h1><%= @topic.name %> Articles</h1>
<div class="row">
  <div class="card-deck">
    <% @articles.each do |article| %>
      <%= link_to topic_article_path(@topic, article) do %>
        <div class="card" style="width: 20rem;">
          <img class="card-img-top" src="<%= article.thumbnail %>" height="90" alt="<%= article.title %>">
          <div class="card-block">
            <h4 class="card-title"><%= article.title %></h4>
            <p class="card-text">By <%= article.author %></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><%= article.created_at %></small>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= link_to "Back to Topics", topics_path, class: "btn btn-primary" %>
<%= link_to "New #{@topic.name} Article", new_topic_article_path(@topic, @article), class: "btn btn-success" %>

app/views/welcome/index.html.erb
<h1>Piano Demo Site Test</h1>
<p>This is a test site for Piano software.</p>

    <div id="slideout">
      <div id="slidecontent">
          Yar, there be dragonns herre!
      </div>
    </div>